// AUTO-GENERATED by release.sh on each BETA release. Do not hand-edit.
// Consumed by the site's small "newest beta" link; the main Download
// button reads lib/latestVersion.ts (stable channel) instead. The link
// hides itself when BETA_BUILD <= LATEST_BUILD (beta promoted/obsolete).
export const BETA_VERSION: string | null = "1.0.7.30";
export const BETA_BUILD: number = 74;
export const BETA_DMG_URL: string | null = `/downloads/Daisy-1.0.7.30.dmg?v=74`;
