// AUTO-GENERATED by release.sh (stable releases + promote). Do not
// hand-edit. Source of truth for the site's main Download button;
// appcast.xml is the source of truth for Sparkle updates.
export const LATEST_VERSION = "1.0.7.29";
export const LATEST_BUILD = 73;
// ?v= is a cache-bust key — see release.sh step [6/6] notes.
export const LATEST_DMG_URL = `/downloads/Daisy-${LATEST_VERSION}.dmg?v=${LATEST_BUILD}`;
