//
//  Summarizer.swift
//  Daisy
//
//  Observable façade for the summarization pipeline. The UI talks to
//  exactly one Summarizer; it dispatches to the user-selected
//  SummaryProvider (Apple Intelligence / Anthropic / OpenAI) under the
//  hood. Keeps `lastSummary`, `isSummarizing`, `lastError`, and
//  `availability` reactive so the SwiftUI views update automatically.
//

import Foundation
import FoundationModels
import Observation
import os

/// Three-section meeting summary:
///  1. `summary` — what the meeting was about (the "встреча" section)
///  2. `actionItems` — block of next steps the participants will take
///  3. `clientFollowUp` — ready-to-send draft message a client or
///     partner could receive (separate from internal action items)
///
/// `decisions` and `followUps` are legacy fields kept solely for
/// backwards-compatible decoding of `summary.json` files written by
/// older builds. They are NOT generated by the current schema (the
/// @Generable annotation only covers the three primary fields) and
/// the UI / exports no longer render them.
@Generable
nonisolated struct MeetingSummary: Codable, Sendable, Equatable {
    @Guide(description: "Concise 2-4 sentence overview of what the meeting was about and what was discussed. Do not invent details not present in the transcript.")
    let summary: String

    @Guide(description: "Block of next actions agreed on during the meeting — what the participants will do after the call ends. Each item in imperative form, e.g. 'Send invoice to client' or 'Review the proposal'. Include the responsible person if explicitly mentioned. Empty array if no clear actions were discussed.")
    let actionItems: [String]

    @Guide(description: "Ready-to-send follow-up message that a client or partner from this meeting could receive. Write in the second person, polite-professional tone, no greeting boilerplate beyond a single short opener. Cover what was discussed and what the next steps are from their perspective. If the meeting was internal-only with no external counterpart, return an empty string. 80-180 words.")
    let clientFollowUp: String

    // ─── Legacy (backwards-compat only) ──────────────────────────────
    //
    // These are NOT in the @Generable schema, so the model doesn't
    // generate them. They exist on the type only so `JSONDecoder` can
    // still read `summary.json` files written by older builds without
    // throwing. New code should not write them.
    let decisions: [String]?
    let followUps: [String]?

    // MARK: - Initialisers

    /// Primary initializer used by current code paths.
    init(summary: String, actionItems: [String], clientFollowUp: String) {
        self.summary = summary
        self.actionItems = actionItems
        self.clientFollowUp = clientFollowUp
        self.decisions = nil
        self.followUps = nil
    }

    // MARK: - Codable

    /// Tolerant decoder: accepts both the current 3-field schema and
    /// the legacy 4-field one. Missing `clientFollowUp` (legacy files)
    /// defaults to empty string — UI hides the section in that case.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.summary = try c.decode(String.self, forKey: .summary)
        self.actionItems = try c.decodeIfPresent([String].self, forKey: .actionItems) ?? []
        self.clientFollowUp = try c.decodeIfPresent(String.self, forKey: .clientFollowUp) ?? ""
        self.decisions = try c.decodeIfPresent([String].self, forKey: .decisions)
        self.followUps = try c.decodeIfPresent([String].self, forKey: .followUps)
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(summary, forKey: .summary)
        try c.encode(actionItems, forKey: .actionItems)
        try c.encode(clientFollowUp, forKey: .clientFollowUp)
        // Legacy fields are intentionally not written.
    }

    private enum CodingKeys: String, CodingKey {
        case summary, actionItems, clientFollowUp, decisions, followUps
    }
}

@Observable
@MainActor
final class Summarizer {
    enum AvailabilityState: Equatable {
        case unknown
        case available
        case unavailable(String)
    }

    /// Shared instance — Summarizer holds the user's provider preference,
    /// API model selections, and the most recent result. Both Settings UI
    /// and RecordingSession bind to the same object.
    static let shared = Summarizer()

    // MARK: - Observable

    private(set) var availability: AvailabilityState = .unknown
    private(set) var isSummarizing = false
    private(set) var lastSummary: MeetingSummary?
    private(set) var lastError: String?

    /// Which provider is currently selected. Persisted to UserDefaults.
    /// Changing it triggers an availability re-check.
    var providerKind: SummaryProviderKind {
        didSet {
            guard oldValue != providerKind else { return }
            UserDefaults.standard.set(providerKind.rawValue, forKey: Self.kProvider)
            Task { await refreshAvailability() }
        }
    }

    /// Model ID selected per cloud provider (Anthropic / OpenAI).
    /// Apple Intelligence has no choice. Persisted independently so the
    /// user's pick survives switching providers back and forth.
    var anthropicModel: String {
        didSet { UserDefaults.standard.set(anthropicModel, forKey: Self.kAnthropicModel) }
    }
    var openaiModel: String {
        didSet { UserDefaults.standard.set(openaiModel, forKey: Self.kOpenAIModel) }
    }

    // MARK: - Private

    @ObservationIgnored
    private let log = Logger(subsystem: "app.essazanov.Daisy", category: "Summarizer")

    private static let kProvider = "daisy.summaryProvider"
    private static let kAnthropicModel = "daisy.anthropicModel"
    private static let kOpenAIModel = "daisy.openaiModel"

    private init() {
        let storedProvider = UserDefaults.standard.string(forKey: Self.kProvider)
            ?? SummaryProviderKind.appleIntelligence.rawValue
        self.providerKind = SummaryProviderKind(rawValue: storedProvider) ?? .appleIntelligence

        self.anthropicModel = UserDefaults.standard.string(forKey: Self.kAnthropicModel)
            ?? AnthropicAPISummarizer.defaultModelID
        self.openaiModel = UserDefaults.standard.string(forKey: Self.kOpenAIModel)
            ?? OpenAIAPISummarizer.defaultModelID

        Task { await refreshAvailability() }
    }

    // MARK: - Availability

    func refreshAvailability() async {
        let provider = makeProvider()
        let ready = await provider.isReady()
        if ready {
            availability = .available
        } else {
            availability = .unavailable(reasonForCurrent())
        }
    }

    private func reasonForCurrent() -> String {
        switch providerKind {
        case .appleIntelligence:
            return "Apple Intelligence is not available on this Mac, not enabled, or still downloading. Check System Settings → Apple Intelligence & Siri, or pick a different provider in Settings → Summary Provider."
        case .anthropic:
            return "Anthropic API key is missing. Add it in Settings → Summary Provider."
        case .openai:
            return "OpenAI API key is missing. Add it in Settings → Summary Provider."
        }
    }

    // MARK: - Summarize

    func summarize(transcript: String, title: String, localeHint: String?) async {
        guard !transcript.isEmpty else { return }
        isSummarizing = true
        lastError = nil

        let provider = makeProvider()
        do {
            let summary = try await provider.summarize(
                transcript: transcript,
                title: title,
                localeHint: localeHint
            )
            lastSummary = summary
            log.info("Summarized via \(self.providerKind.shortName, privacy: .public)")
        } catch {
            log.error("Summarize failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
        isSummarizing = false
    }

    func clear() {
        lastSummary = nil
        lastError = nil
    }

    // MARK: - Factory

    /// Build a provider instance for the currently selected kind.
    /// Cheap to make — providers are structs/lightweight classes that
    /// hold no expensive state beyond URLSession references.
    private func makeProvider() -> SummaryProvider {
        switch providerKind {
        case .appleIntelligence:
            return AppleIntelligenceSummarizer()
        case .anthropic:
            return AnthropicAPISummarizer(model: anthropicModel)
        case .openai:
            return OpenAIAPISummarizer(model: openaiModel)
        }
    }
}
